favicon: null
name: T-80-T
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.5597559979651123
  brandStrength: 0.4144389275461435
  rhythmicContrast: 0.4082777856383473
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  lightness: 0.1968099381774664
typography_spectrum: 0.4390681
layout_spectrum: 0.6666667
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
